from tkinter import *
root = Tk()
root.geometry('655x333')
f1 = Frame(root, bg='grey', borderwidth=6, relief=SUNKEN)
f1.pack(side=LEFT, fill=Y)
f2 = Frame(root, borderwidth=9, bg='grey', relief=SUNKEN)
f2.pack(side=TOP, fill=X)
l1 = Label(f1, text='Project Tkinter - Pycharm')
l1.pack(pady=142)
l2 = Label(f2, text='Welcome to Sublime Text', font="Helvetica 16 bold", fg="red")
l2.pack(fill=X)
root.mainloop()