from tkinter import *
import pandas as pd
root = Tk()
root.geometry("644x344") 
def GetVals():
    nameval = nameentry.get()
    phoneval = phoneentry.get()
    genderval = genderentry.get()
    emergencyval = emrgencyentry.get()
    paymentmodeval = paymentmodeentry.get()
    foodserviceval = foodservicevalue.get()
    Data = pd.DataFrame([[nameval, phoneval, genderval, emergencyval, paymentmodeval, foodserviceval]], columns=['Name', 'Phone', 'Gender', 'Emergency No.', 'Payment Mode', 'Meal'])
    Data.to_csv(f'{nameval}.csv')
    print('Value Submited Successfuly')
name = Label(root, text="Name")
phone = Label(root, text="Phone")
gender = Label(root, text="Gender")
emergency = Label(root, text="Emergency Contact")
paymentmode = Label(root, text="Payment Mode")

name.grid(row=1, column=2)
phone.grid(row=2, column=2)
gender.grid(row=3, column=2)
emergency.grid(row=4, column=2)
paymentmode.grid(row=5, column=2)

namevalue = StringVar()
phonevalue = StringVar()
gendervalue = StringVar()
emergencyvalue = StringVar()
paymentmodevalue = StringVar()
foodservicevalue = IntVar()

nameentry = Entry(root, textvariable=namevalue)
phoneentry = Entry(root, textvariable=phonevalue)
genderentry = Entry(root, textvariable=gendervalue)
emrgencyentry = Entry(root, textvariable=emergencyvalue)
paymentmodeentry = Entry(root, textvariable=paymentmodevalue)
foodserviceentry = Checkbutton(root, text='Do you want your meals', variable=foodservicevalue)

nameentry.grid(row=1, column=90)
phoneentry.grid(row=2, column=90)
genderentry.grid(row=3, column=90)
emrgencyentry.grid(row=4, column=90)
paymentmodeentry.grid(row=5, column=90)
foodserviceentry.grid(row=6, column=90)

Button = Button(text='Submit', fg='white', bg='blue',  command=GetVals)
Button.grid(row=7, column=90)
root.mainloop()